################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/kerem/OneDrive/Documents/stm32-prototype/BLESensorsPnPL/Drivers/BSP/STWIN.box/STWIN.box_audio.c \
C:/Users/kerem/OneDrive/Documents/stm32-prototype/BLESensorsPnPL/Drivers/BSP/STWIN.box/STWIN.box_bc.c \
C:/Users/kerem/OneDrive/Documents/stm32-prototype/BLESensorsPnPL/Drivers/BSP/STWIN.box/STWIN.box_debug_pins.c \
C:/Users/kerem/OneDrive/Documents/stm32-prototype/BLESensorsPnPL/Drivers/BSP/STWIN.box/STWIN.box_env_sensors.c \
C:/Users/kerem/OneDrive/Documents/stm32-prototype/BLESensorsPnPL/Drivers/BSP/STWIN.box/STWIN.box_env_sensors_ex.c \
C:/Users/kerem/OneDrive/Documents/stm32-prototype/BLESensorsPnPL/Drivers/BSP/STWIN.box/STWIN.box_motion_sensors.c \
C:/Users/kerem/OneDrive/Documents/stm32-prototype/BLESensorsPnPL/Drivers/BSP/STWIN.box/STWIN.box_motion_sensors_ex.c \
C:/Users/kerem/OneDrive/Documents/stm32-prototype/BLESensorsPnPL/Drivers/BSP/STWIN.box/STWIN.box_nfctag.c \
C:/Users/kerem/OneDrive/Documents/stm32-prototype/BLESensorsPnPL/Drivers/BSP/STWIN.box/STWIN.box_sd.c 

OBJS += \
./Drivers/BSP/STWIN.box/STWIN.box_audio.o \
./Drivers/BSP/STWIN.box/STWIN.box_bc.o \
./Drivers/BSP/STWIN.box/STWIN.box_debug_pins.o \
./Drivers/BSP/STWIN.box/STWIN.box_env_sensors.o \
./Drivers/BSP/STWIN.box/STWIN.box_env_sensors_ex.o \
./Drivers/BSP/STWIN.box/STWIN.box_motion_sensors.o \
./Drivers/BSP/STWIN.box/STWIN.box_motion_sensors_ex.o \
./Drivers/BSP/STWIN.box/STWIN.box_nfctag.o \
./Drivers/BSP/STWIN.box/STWIN.box_sd.o 

C_DEPS += \
./Drivers/BSP/STWIN.box/STWIN.box_audio.d \
./Drivers/BSP/STWIN.box/STWIN.box_bc.d \
./Drivers/BSP/STWIN.box/STWIN.box_debug_pins.d \
./Drivers/BSP/STWIN.box/STWIN.box_env_sensors.d \
./Drivers/BSP/STWIN.box/STWIN.box_env_sensors_ex.d \
./Drivers/BSP/STWIN.box/STWIN.box_motion_sensors.d \
./Drivers/BSP/STWIN.box/STWIN.box_motion_sensors_ex.d \
./Drivers/BSP/STWIN.box/STWIN.box_nfctag.d \
./Drivers/BSP/STWIN.box/STWIN.box_sd.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/BSP/STWIN.box/STWIN.box_audio.o: C:/Users/kerem/OneDrive/Documents/stm32-prototype/BLESensorsPnPL/Drivers/BSP/STWIN.box/STWIN.box_audio.c Drivers/BSP/STWIN.box/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U585xx -c -I../../Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/STM32_BLE_Manager/Inc -I../../Middlewares/Third_Party/parson -I../../Drivers/BSP/STWIN.box -I../../Drivers/BSP/Components/Common -I../../Middlewares/ST/PnPLCompManager/Inc -I../../Middlewares/ST/BlueNRG-2/hci/hci_tl_patterns/Basic -I../../Middlewares/ST/BlueNRG-2/utils -I../../Middlewares/ST/BlueNRG-2/includes -I../../Drivers/BSP/Components/ism330dhcx -I../../Drivers/BSP/Components/iis2mdc -I../../Drivers/BSP/Components/iis2dlpc -I../../Drivers/BSP/Components/iis2iclx -I../../Drivers/BSP/Components/iis3dwb -I../../Drivers/BSP/Components/stts22h -I../../Drivers/BSP/Components/ilps22qs -I../../Drivers/BSP/Components/ST25DV -O0 -ffunction-sections -fdata-sections -Wall -Wno-format -Wno-enum-compare -Wno-enum-conversion -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/STWIN.box/STWIN.box_bc.o: C:/Users/kerem/OneDrive/Documents/stm32-prototype/BLESensorsPnPL/Drivers/BSP/STWIN.box/STWIN.box_bc.c Drivers/BSP/STWIN.box/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U585xx -c -I../../Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/STM32_BLE_Manager/Inc -I../../Middlewares/Third_Party/parson -I../../Drivers/BSP/STWIN.box -I../../Drivers/BSP/Components/Common -I../../Middlewares/ST/PnPLCompManager/Inc -I../../Middlewares/ST/BlueNRG-2/hci/hci_tl_patterns/Basic -I../../Middlewares/ST/BlueNRG-2/utils -I../../Middlewares/ST/BlueNRG-2/includes -I../../Drivers/BSP/Components/ism330dhcx -I../../Drivers/BSP/Components/iis2mdc -I../../Drivers/BSP/Components/iis2dlpc -I../../Drivers/BSP/Components/iis2iclx -I../../Drivers/BSP/Components/iis3dwb -I../../Drivers/BSP/Components/stts22h -I../../Drivers/BSP/Components/ilps22qs -I../../Drivers/BSP/Components/ST25DV -O0 -ffunction-sections -fdata-sections -Wall -Wno-format -Wno-enum-compare -Wno-enum-conversion -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/STWIN.box/STWIN.box_debug_pins.o: C:/Users/kerem/OneDrive/Documents/stm32-prototype/BLESensorsPnPL/Drivers/BSP/STWIN.box/STWIN.box_debug_pins.c Drivers/BSP/STWIN.box/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U585xx -c -I../../Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/STM32_BLE_Manager/Inc -I../../Middlewares/Third_Party/parson -I../../Drivers/BSP/STWIN.box -I../../Drivers/BSP/Components/Common -I../../Middlewares/ST/PnPLCompManager/Inc -I../../Middlewares/ST/BlueNRG-2/hci/hci_tl_patterns/Basic -I../../Middlewares/ST/BlueNRG-2/utils -I../../Middlewares/ST/BlueNRG-2/includes -I../../Drivers/BSP/Components/ism330dhcx -I../../Drivers/BSP/Components/iis2mdc -I../../Drivers/BSP/Components/iis2dlpc -I../../Drivers/BSP/Components/iis2iclx -I../../Drivers/BSP/Components/iis3dwb -I../../Drivers/BSP/Components/stts22h -I../../Drivers/BSP/Components/ilps22qs -I../../Drivers/BSP/Components/ST25DV -O0 -ffunction-sections -fdata-sections -Wall -Wno-format -Wno-enum-compare -Wno-enum-conversion -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/STWIN.box/STWIN.box_env_sensors.o: C:/Users/kerem/OneDrive/Documents/stm32-prototype/BLESensorsPnPL/Drivers/BSP/STWIN.box/STWIN.box_env_sensors.c Drivers/BSP/STWIN.box/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U585xx -c -I../../Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/STM32_BLE_Manager/Inc -I../../Middlewares/Third_Party/parson -I../../Drivers/BSP/STWIN.box -I../../Drivers/BSP/Components/Common -I../../Middlewares/ST/PnPLCompManager/Inc -I../../Middlewares/ST/BlueNRG-2/hci/hci_tl_patterns/Basic -I../../Middlewares/ST/BlueNRG-2/utils -I../../Middlewares/ST/BlueNRG-2/includes -I../../Drivers/BSP/Components/ism330dhcx -I../../Drivers/BSP/Components/iis2mdc -I../../Drivers/BSP/Components/iis2dlpc -I../../Drivers/BSP/Components/iis2iclx -I../../Drivers/BSP/Components/iis3dwb -I../../Drivers/BSP/Components/stts22h -I../../Drivers/BSP/Components/ilps22qs -I../../Drivers/BSP/Components/ST25DV -O0 -ffunction-sections -fdata-sections -Wall -Wno-format -Wno-enum-compare -Wno-enum-conversion -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/STWIN.box/STWIN.box_env_sensors_ex.o: C:/Users/kerem/OneDrive/Documents/stm32-prototype/BLESensorsPnPL/Drivers/BSP/STWIN.box/STWIN.box_env_sensors_ex.c Drivers/BSP/STWIN.box/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U585xx -c -I../../Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/STM32_BLE_Manager/Inc -I../../Middlewares/Third_Party/parson -I../../Drivers/BSP/STWIN.box -I../../Drivers/BSP/Components/Common -I../../Middlewares/ST/PnPLCompManager/Inc -I../../Middlewares/ST/BlueNRG-2/hci/hci_tl_patterns/Basic -I../../Middlewares/ST/BlueNRG-2/utils -I../../Middlewares/ST/BlueNRG-2/includes -I../../Drivers/BSP/Components/ism330dhcx -I../../Drivers/BSP/Components/iis2mdc -I../../Drivers/BSP/Components/iis2dlpc -I../../Drivers/BSP/Components/iis2iclx -I../../Drivers/BSP/Components/iis3dwb -I../../Drivers/BSP/Components/stts22h -I../../Drivers/BSP/Components/ilps22qs -I../../Drivers/BSP/Components/ST25DV -O0 -ffunction-sections -fdata-sections -Wall -Wno-format -Wno-enum-compare -Wno-enum-conversion -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/STWIN.box/STWIN.box_motion_sensors.o: C:/Users/kerem/OneDrive/Documents/stm32-prototype/BLESensorsPnPL/Drivers/BSP/STWIN.box/STWIN.box_motion_sensors.c Drivers/BSP/STWIN.box/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U585xx -c -I../../Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/STM32_BLE_Manager/Inc -I../../Middlewares/Third_Party/parson -I../../Drivers/BSP/STWIN.box -I../../Drivers/BSP/Components/Common -I../../Middlewares/ST/PnPLCompManager/Inc -I../../Middlewares/ST/BlueNRG-2/hci/hci_tl_patterns/Basic -I../../Middlewares/ST/BlueNRG-2/utils -I../../Middlewares/ST/BlueNRG-2/includes -I../../Drivers/BSP/Components/ism330dhcx -I../../Drivers/BSP/Components/iis2mdc -I../../Drivers/BSP/Components/iis2dlpc -I../../Drivers/BSP/Components/iis2iclx -I../../Drivers/BSP/Components/iis3dwb -I../../Drivers/BSP/Components/stts22h -I../../Drivers/BSP/Components/ilps22qs -I../../Drivers/BSP/Components/ST25DV -O0 -ffunction-sections -fdata-sections -Wall -Wno-format -Wno-enum-compare -Wno-enum-conversion -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/STWIN.box/STWIN.box_motion_sensors_ex.o: C:/Users/kerem/OneDrive/Documents/stm32-prototype/BLESensorsPnPL/Drivers/BSP/STWIN.box/STWIN.box_motion_sensors_ex.c Drivers/BSP/STWIN.box/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U585xx -c -I../../Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/STM32_BLE_Manager/Inc -I../../Middlewares/Third_Party/parson -I../../Drivers/BSP/STWIN.box -I../../Drivers/BSP/Components/Common -I../../Middlewares/ST/PnPLCompManager/Inc -I../../Middlewares/ST/BlueNRG-2/hci/hci_tl_patterns/Basic -I../../Middlewares/ST/BlueNRG-2/utils -I../../Middlewares/ST/BlueNRG-2/includes -I../../Drivers/BSP/Components/ism330dhcx -I../../Drivers/BSP/Components/iis2mdc -I../../Drivers/BSP/Components/iis2dlpc -I../../Drivers/BSP/Components/iis2iclx -I../../Drivers/BSP/Components/iis3dwb -I../../Drivers/BSP/Components/stts22h -I../../Drivers/BSP/Components/ilps22qs -I../../Drivers/BSP/Components/ST25DV -O0 -ffunction-sections -fdata-sections -Wall -Wno-format -Wno-enum-compare -Wno-enum-conversion -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/STWIN.box/STWIN.box_nfctag.o: C:/Users/kerem/OneDrive/Documents/stm32-prototype/BLESensorsPnPL/Drivers/BSP/STWIN.box/STWIN.box_nfctag.c Drivers/BSP/STWIN.box/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U585xx -c -I../../Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/STM32_BLE_Manager/Inc -I../../Middlewares/Third_Party/parson -I../../Drivers/BSP/STWIN.box -I../../Drivers/BSP/Components/Common -I../../Middlewares/ST/PnPLCompManager/Inc -I../../Middlewares/ST/BlueNRG-2/hci/hci_tl_patterns/Basic -I../../Middlewares/ST/BlueNRG-2/utils -I../../Middlewares/ST/BlueNRG-2/includes -I../../Drivers/BSP/Components/ism330dhcx -I../../Drivers/BSP/Components/iis2mdc -I../../Drivers/BSP/Components/iis2dlpc -I../../Drivers/BSP/Components/iis2iclx -I../../Drivers/BSP/Components/iis3dwb -I../../Drivers/BSP/Components/stts22h -I../../Drivers/BSP/Components/ilps22qs -I../../Drivers/BSP/Components/ST25DV -O0 -ffunction-sections -fdata-sections -Wall -Wno-format -Wno-enum-compare -Wno-enum-conversion -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/STWIN.box/STWIN.box_sd.o: C:/Users/kerem/OneDrive/Documents/stm32-prototype/BLESensorsPnPL/Drivers/BSP/STWIN.box/STWIN.box_sd.c Drivers/BSP/STWIN.box/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U585xx -c -I../../Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/STM32_BLE_Manager/Inc -I../../Middlewares/Third_Party/parson -I../../Drivers/BSP/STWIN.box -I../../Drivers/BSP/Components/Common -I../../Middlewares/ST/PnPLCompManager/Inc -I../../Middlewares/ST/BlueNRG-2/hci/hci_tl_patterns/Basic -I../../Middlewares/ST/BlueNRG-2/utils -I../../Middlewares/ST/BlueNRG-2/includes -I../../Drivers/BSP/Components/ism330dhcx -I../../Drivers/BSP/Components/iis2mdc -I../../Drivers/BSP/Components/iis2dlpc -I../../Drivers/BSP/Components/iis2iclx -I../../Drivers/BSP/Components/iis3dwb -I../../Drivers/BSP/Components/stts22h -I../../Drivers/BSP/Components/ilps22qs -I../../Drivers/BSP/Components/ST25DV -O0 -ffunction-sections -fdata-sections -Wall -Wno-format -Wno-enum-compare -Wno-enum-conversion -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Drivers-2f-BSP-2f-STWIN-2e-box

clean-Drivers-2f-BSP-2f-STWIN-2e-box:
	-$(RM) ./Drivers/BSP/STWIN.box/STWIN.box_audio.cyclo ./Drivers/BSP/STWIN.box/STWIN.box_audio.d ./Drivers/BSP/STWIN.box/STWIN.box_audio.o ./Drivers/BSP/STWIN.box/STWIN.box_audio.su ./Drivers/BSP/STWIN.box/STWIN.box_bc.cyclo ./Drivers/BSP/STWIN.box/STWIN.box_bc.d ./Drivers/BSP/STWIN.box/STWIN.box_bc.o ./Drivers/BSP/STWIN.box/STWIN.box_bc.su ./Drivers/BSP/STWIN.box/STWIN.box_debug_pins.cyclo ./Drivers/BSP/STWIN.box/STWIN.box_debug_pins.d ./Drivers/BSP/STWIN.box/STWIN.box_debug_pins.o ./Drivers/BSP/STWIN.box/STWIN.box_debug_pins.su ./Drivers/BSP/STWIN.box/STWIN.box_env_sensors.cyclo ./Drivers/BSP/STWIN.box/STWIN.box_env_sensors.d ./Drivers/BSP/STWIN.box/STWIN.box_env_sensors.o ./Drivers/BSP/STWIN.box/STWIN.box_env_sensors.su ./Drivers/BSP/STWIN.box/STWIN.box_env_sensors_ex.cyclo ./Drivers/BSP/STWIN.box/STWIN.box_env_sensors_ex.d ./Drivers/BSP/STWIN.box/STWIN.box_env_sensors_ex.o ./Drivers/BSP/STWIN.box/STWIN.box_env_sensors_ex.su ./Drivers/BSP/STWIN.box/STWIN.box_motion_sensors.cyclo ./Drivers/BSP/STWIN.box/STWIN.box_motion_sensors.d ./Drivers/BSP/STWIN.box/STWIN.box_motion_sensors.o ./Drivers/BSP/STWIN.box/STWIN.box_motion_sensors.su ./Drivers/BSP/STWIN.box/STWIN.box_motion_sensors_ex.cyclo ./Drivers/BSP/STWIN.box/STWIN.box_motion_sensors_ex.d ./Drivers/BSP/STWIN.box/STWIN.box_motion_sensors_ex.o ./Drivers/BSP/STWIN.box/STWIN.box_motion_sensors_ex.su ./Drivers/BSP/STWIN.box/STWIN.box_nfctag.cyclo ./Drivers/BSP/STWIN.box/STWIN.box_nfctag.d ./Drivers/BSP/STWIN.box/STWIN.box_nfctag.o ./Drivers/BSP/STWIN.box/STWIN.box_nfctag.su ./Drivers/BSP/STWIN.box/STWIN.box_sd.cyclo ./Drivers/BSP/STWIN.box/STWIN.box_sd.d ./Drivers/BSP/STWIN.box/STWIN.box_sd.o ./Drivers/BSP/STWIN.box/STWIN.box_sd.su

.PHONY: clean-Drivers-2f-BSP-2f-STWIN-2e-box

